spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: root
  batch:
    initialize-schema: always
app:
  datasource:
  jdbcUrl: jdbc:mysql://localhost:3306/app
  username: root
  password: root

job:
  chunkSize: 20
  limit: 40
  pageSize: 20